<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <RootNamespace>L13.App</RootNamespace>
    <AssemblyName>L13Printer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\L13.Core\L13.Core.csproj" />
  </ItemGroup>

</Project>
